name: Auto Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出 Fork 仓库
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 配置 Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 检查并同步上游仓库
        run: |
          git remote add upstream https://github.com/cmliu/CF-Workers-docker.io.git
          git fetch upstream
          git checkout main
          MERGE_OUTPUT=$(git merge upstream/main --allow-unrelated-histories 2>&1)
          echo "lalalallal-----$MERGE_OUTPUT"

          if echo "$MERGE_OUTPUT" | grep -q "Your branch is up to date"; then
            echo "Merge result: No new updates."
            echo "updated=false" >> $GITHUB_ENV
          else
            echo "Merge result: New updates detected!"
            echo "updated=true" >> $GITHUB_ENV
          fi

      - name: 推送同步后的代码到 Fork
        if: env.updated == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
