name: Auto Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出 Fork 仓库
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 配置 Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 检查并同步上游仓库
        run: |
          git remote add upstream https://github.com/cmliu/CF-Workers-docker.io.git
          git fetch upstream
          LOCAL=$(git rev-parse HEAD)
          REMOTE=$(git rev-parse upstream/main)
          if [ "$LOCAL" != "$REMOTE" ]; then
            git checkout main
            git merge upstream/main --allow-unrelated-histories || echo "No changes to merge"
            git push origin main
          else
            echo "No updates found."
          fi
