name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/cmliu/CF-Workers-docker.io.git
          git fetch upstream

      - name: Merge upstream
        run: |
          git checkout main
          git merge upstream/main

      - name: Push changes
        run: |
          git push origin main
